WITH CONTRACTS_CTE (CTRCUSTOMERID, NUMBEROFCONTRACTS) AS (
  SELECT
    CUSTOMER_ID
    , COUNT(*)
  FROM CONTRACTS
  GROUP BY CUSTOMER_ID
)

SELECT AVG(NUMBEROFCONTRACTS) AS AVERAGE
FROM CONTRACTS_CTE;
